// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sd_times.proto

package com.protos;

public final class TimesProtos {
  private TimesProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TimeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.protos.Time)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>string nome = 2;</code>
     */
    java.lang.String getNome();
    /**
     * <code>string nome = 2;</code>
     */
    com.google.protobuf.ByteString
        getNomeBytes();

    /**
     * <code>string data = 3;</code>
     */
    java.lang.String getData();
    /**
     * <code>string data = 3;</code>
     */
    com.google.protobuf.ByteString
        getDataBytes();

    /**
     * <code>string titulos = 4;</code>
     */
    java.lang.String getTitulos();
    /**
     * <code>string titulos = 4;</code>
     */
    com.google.protobuf.ByteString
        getTitulosBytes();
  }
  /**
   * Protobuf type {@code com.protos.Time}
   */
  public  static final class Time extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.protos.Time)
      TimeOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Time.newBuilder() to construct.
    private Time(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Time() {
      id_ = 0;
      nome_ = "";
      data_ = "";
      titulos_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Time(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              nome_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              data_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              titulos_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.protos.TimesProtos.internal_static_com_protos_Time_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.protos.TimesProtos.internal_static_com_protos_Time_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.protos.TimesProtos.Time.class, com.protos.TimesProtos.Time.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int NOME_FIELD_NUMBER = 2;
    private volatile java.lang.Object nome_;
    /**
     * <code>string nome = 2;</code>
     */
    public java.lang.String getNome() {
      java.lang.Object ref = nome_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nome_ = s;
        return s;
      }
    }
    /**
     * <code>string nome = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNomeBytes() {
      java.lang.Object ref = nome_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nome_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATA_FIELD_NUMBER = 3;
    private volatile java.lang.Object data_;
    /**
     * <code>string data = 3;</code>
     */
    public java.lang.String getData() {
      java.lang.Object ref = data_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        data_ = s;
        return s;
      }
    }
    /**
     * <code>string data = 3;</code>
     */
    public com.google.protobuf.ByteString
        getDataBytes() {
      java.lang.Object ref = data_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        data_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TITULOS_FIELD_NUMBER = 4;
    private volatile java.lang.Object titulos_;
    /**
     * <code>string titulos = 4;</code>
     */
    public java.lang.String getTitulos() {
      java.lang.Object ref = titulos_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        titulos_ = s;
        return s;
      }
    }
    /**
     * <code>string titulos = 4;</code>
     */
    public com.google.protobuf.ByteString
        getTitulosBytes() {
      java.lang.Object ref = titulos_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        titulos_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!getNomeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, nome_);
      }
      if (!getDataBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, data_);
      }
      if (!getTitulosBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, titulos_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!getNomeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, nome_);
      }
      if (!getDataBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, data_);
      }
      if (!getTitulosBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, titulos_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.protos.TimesProtos.Time)) {
        return super.equals(obj);
      }
      com.protos.TimesProtos.Time other = (com.protos.TimesProtos.Time) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && getNome()
          .equals(other.getNome());
      result = result && getData()
          .equals(other.getData());
      result = result && getTitulos()
          .equals(other.getTitulos());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + NOME_FIELD_NUMBER;
      hash = (53 * hash) + getNome().hashCode();
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (37 * hash) + TITULOS_FIELD_NUMBER;
      hash = (53 * hash) + getTitulos().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.protos.TimesProtos.Time parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protos.TimesProtos.Time parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protos.TimesProtos.Time parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protos.TimesProtos.Time parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protos.TimesProtos.Time parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protos.TimesProtos.Time parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protos.TimesProtos.Time parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.protos.TimesProtos.Time parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.protos.TimesProtos.Time parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.protos.TimesProtos.Time parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.protos.TimesProtos.Time parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.protos.TimesProtos.Time parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.protos.TimesProtos.Time prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.protos.Time}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.protos.Time)
        com.protos.TimesProtos.TimeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.protos.TimesProtos.internal_static_com_protos_Time_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.protos.TimesProtos.internal_static_com_protos_Time_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.protos.TimesProtos.Time.class, com.protos.TimesProtos.Time.Builder.class);
      }

      // Construct using com.protos.TimesProtos.Time.newBuilder()
      public Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0;

        nome_ = "";

        data_ = "";

        titulos_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.protos.TimesProtos.internal_static_com_protos_Time_descriptor;
      }

      public com.protos.TimesProtos.Time getDefaultInstanceForType() {
        return com.protos.TimesProtos.Time.getDefaultInstance();
      }

      public com.protos.TimesProtos.Time build() {
        com.protos.TimesProtos.Time result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.protos.TimesProtos.Time buildPartial() {
        com.protos.TimesProtos.Time result = new com.protos.TimesProtos.Time(this);
        result.id_ = id_;
        result.nome_ = nome_;
        result.data_ = data_;
        result.titulos_ = titulos_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.protos.TimesProtos.Time) {
          return mergeFrom((com.protos.TimesProtos.Time)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.protos.TimesProtos.Time other) {
        if (other == com.protos.TimesProtos.Time.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getNome().isEmpty()) {
          nome_ = other.nome_;
          onChanged();
        }
        if (!other.getData().isEmpty()) {
          data_ = other.data_;
          onChanged();
        }
        if (!other.getTitulos().isEmpty()) {
          titulos_ = other.titulos_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.protos.TimesProtos.Time parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.protos.TimesProtos.Time) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object nome_ = "";
      /**
       * <code>string nome = 2;</code>
       */
      public java.lang.String getNome() {
        java.lang.Object ref = nome_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          nome_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string nome = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNomeBytes() {
        java.lang.Object ref = nome_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nome_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string nome = 2;</code>
       */
      public Builder setNome(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        nome_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string nome = 2;</code>
       */
      public Builder clearNome() {
        
        nome_ = getDefaultInstance().getNome();
        onChanged();
        return this;
      }
      /**
       * <code>string nome = 2;</code>
       */
      public Builder setNomeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        nome_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object data_ = "";
      /**
       * <code>string data = 3;</code>
       */
      public java.lang.String getData() {
        java.lang.Object ref = data_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          data_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string data = 3;</code>
       */
      public com.google.protobuf.ByteString
          getDataBytes() {
        java.lang.Object ref = data_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          data_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string data = 3;</code>
       */
      public Builder setData(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string data = 3;</code>
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      /**
       * <code>string data = 3;</code>
       */
      public Builder setDataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        data_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object titulos_ = "";
      /**
       * <code>string titulos = 4;</code>
       */
      public java.lang.String getTitulos() {
        java.lang.Object ref = titulos_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          titulos_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string titulos = 4;</code>
       */
      public com.google.protobuf.ByteString
          getTitulosBytes() {
        java.lang.Object ref = titulos_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          titulos_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string titulos = 4;</code>
       */
      public Builder setTitulos(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        titulos_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string titulos = 4;</code>
       */
      public Builder clearTitulos() {
        
        titulos_ = getDefaultInstance().getTitulos();
        onChanged();
        return this;
      }
      /**
       * <code>string titulos = 4;</code>
       */
      public Builder setTitulosBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        titulos_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.protos.Time)
    }

    // @@protoc_insertion_point(class_scope:com.protos.Time)
    private static final com.protos.TimesProtos.Time DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.protos.TimesProtos.Time();
    }

    public static com.protos.TimesProtos.Time getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Time>
        PARSER = new com.google.protobuf.AbstractParser<Time>() {
      public Time parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Time(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Time> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Time> getParserForType() {
      return PARSER;
    }

    public com.protos.TimesProtos.Time getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TimesOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.protos.Times)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .com.protos.Time time = 1;</code>
     */
    java.util.List<com.protos.TimesProtos.Time> 
        getTimeList();
    /**
     * <code>repeated .com.protos.Time time = 1;</code>
     */
    com.protos.TimesProtos.Time getTime(int index);
    /**
     * <code>repeated .com.protos.Time time = 1;</code>
     */
    int getTimeCount();
    /**
     * <code>repeated .com.protos.Time time = 1;</code>
     */
    java.util.List<? extends com.protos.TimesProtos.TimeOrBuilder> 
        getTimeOrBuilderList();
    /**
     * <code>repeated .com.protos.Time time = 1;</code>
     */
    com.protos.TimesProtos.TimeOrBuilder getTimeOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.protos.Times}
   */
  public  static final class Times extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.protos.Times)
      TimesOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Times.newBuilder() to construct.
    private Times(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Times() {
      time_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Times(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                time_ = new java.util.ArrayList<com.protos.TimesProtos.Time>();
                mutable_bitField0_ |= 0x00000001;
              }
              time_.add(
                  input.readMessage(com.protos.TimesProtos.Time.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          time_ = java.util.Collections.unmodifiableList(time_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.protos.TimesProtos.internal_static_com_protos_Times_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.protos.TimesProtos.internal_static_com_protos_Times_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.protos.TimesProtos.Times.class, com.protos.TimesProtos.Times.Builder.class);
    }

    public static final int TIME_FIELD_NUMBER = 1;
    private java.util.List<com.protos.TimesProtos.Time> time_;
    /**
     * <code>repeated .com.protos.Time time = 1;</code>
     */
    public java.util.List<com.protos.TimesProtos.Time> getTimeList() {
      return time_;
    }
    /**
     * <code>repeated .com.protos.Time time = 1;</code>
     */
    public java.util.List<? extends com.protos.TimesProtos.TimeOrBuilder> 
        getTimeOrBuilderList() {
      return time_;
    }
    /**
     * <code>repeated .com.protos.Time time = 1;</code>
     */
    public int getTimeCount() {
      return time_.size();
    }
    /**
     * <code>repeated .com.protos.Time time = 1;</code>
     */
    public com.protos.TimesProtos.Time getTime(int index) {
      return time_.get(index);
    }
    /**
     * <code>repeated .com.protos.Time time = 1;</code>
     */
    public com.protos.TimesProtos.TimeOrBuilder getTimeOrBuilder(
        int index) {
      return time_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < time_.size(); i++) {
        output.writeMessage(1, time_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < time_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, time_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.protos.TimesProtos.Times)) {
        return super.equals(obj);
      }
      com.protos.TimesProtos.Times other = (com.protos.TimesProtos.Times) obj;

      boolean result = true;
      result = result && getTimeList()
          .equals(other.getTimeList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getTimeCount() > 0) {
        hash = (37 * hash) + TIME_FIELD_NUMBER;
        hash = (53 * hash) + getTimeList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.protos.TimesProtos.Times parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protos.TimesProtos.Times parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protos.TimesProtos.Times parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protos.TimesProtos.Times parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protos.TimesProtos.Times parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protos.TimesProtos.Times parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protos.TimesProtos.Times parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.protos.TimesProtos.Times parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.protos.TimesProtos.Times parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.protos.TimesProtos.Times parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.protos.TimesProtos.Times parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.protos.TimesProtos.Times parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.protos.TimesProtos.Times prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.protos.Times}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.protos.Times)
        com.protos.TimesProtos.TimesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.protos.TimesProtos.internal_static_com_protos_Times_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.protos.TimesProtos.internal_static_com_protos_Times_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.protos.TimesProtos.Times.class, com.protos.TimesProtos.Times.Builder.class);
      }

      // Construct using com.protos.TimesProtos.Times.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getTimeFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (timeBuilder_ == null) {
          time_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          timeBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.protos.TimesProtos.internal_static_com_protos_Times_descriptor;
      }

      public com.protos.TimesProtos.Times getDefaultInstanceForType() {
        return com.protos.TimesProtos.Times.getDefaultInstance();
      }

      public com.protos.TimesProtos.Times build() {
        com.protos.TimesProtos.Times result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.protos.TimesProtos.Times buildPartial() {
        com.protos.TimesProtos.Times result = new com.protos.TimesProtos.Times(this);
        int from_bitField0_ = bitField0_;
        if (timeBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            time_ = java.util.Collections.unmodifiableList(time_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.time_ = time_;
        } else {
          result.time_ = timeBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.protos.TimesProtos.Times) {
          return mergeFrom((com.protos.TimesProtos.Times)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.protos.TimesProtos.Times other) {
        if (other == com.protos.TimesProtos.Times.getDefaultInstance()) return this;
        if (timeBuilder_ == null) {
          if (!other.time_.isEmpty()) {
            if (time_.isEmpty()) {
              time_ = other.time_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureTimeIsMutable();
              time_.addAll(other.time_);
            }
            onChanged();
          }
        } else {
          if (!other.time_.isEmpty()) {
            if (timeBuilder_.isEmpty()) {
              timeBuilder_.dispose();
              timeBuilder_ = null;
              time_ = other.time_;
              bitField0_ = (bitField0_ & ~0x00000001);
              timeBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getTimeFieldBuilder() : null;
            } else {
              timeBuilder_.addAllMessages(other.time_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.protos.TimesProtos.Times parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.protos.TimesProtos.Times) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.protos.TimesProtos.Time> time_ =
        java.util.Collections.emptyList();
      private void ensureTimeIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          time_ = new java.util.ArrayList<com.protos.TimesProtos.Time>(time_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.protos.TimesProtos.Time, com.protos.TimesProtos.Time.Builder, com.protos.TimesProtos.TimeOrBuilder> timeBuilder_;

      /**
       * <code>repeated .com.protos.Time time = 1;</code>
       */
      public java.util.List<com.protos.TimesProtos.Time> getTimeList() {
        if (timeBuilder_ == null) {
          return java.util.Collections.unmodifiableList(time_);
        } else {
          return timeBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.protos.Time time = 1;</code>
       */
      public int getTimeCount() {
        if (timeBuilder_ == null) {
          return time_.size();
        } else {
          return timeBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.protos.Time time = 1;</code>
       */
      public com.protos.TimesProtos.Time getTime(int index) {
        if (timeBuilder_ == null) {
          return time_.get(index);
        } else {
          return timeBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.protos.Time time = 1;</code>
       */
      public Builder setTime(
          int index, com.protos.TimesProtos.Time value) {
        if (timeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTimeIsMutable();
          time_.set(index, value);
          onChanged();
        } else {
          timeBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.protos.Time time = 1;</code>
       */
      public Builder setTime(
          int index, com.protos.TimesProtos.Time.Builder builderForValue) {
        if (timeBuilder_ == null) {
          ensureTimeIsMutable();
          time_.set(index, builderForValue.build());
          onChanged();
        } else {
          timeBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.protos.Time time = 1;</code>
       */
      public Builder addTime(com.protos.TimesProtos.Time value) {
        if (timeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTimeIsMutable();
          time_.add(value);
          onChanged();
        } else {
          timeBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.protos.Time time = 1;</code>
       */
      public Builder addTime(
          int index, com.protos.TimesProtos.Time value) {
        if (timeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTimeIsMutable();
          time_.add(index, value);
          onChanged();
        } else {
          timeBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.protos.Time time = 1;</code>
       */
      public Builder addTime(
          com.protos.TimesProtos.Time.Builder builderForValue) {
        if (timeBuilder_ == null) {
          ensureTimeIsMutable();
          time_.add(builderForValue.build());
          onChanged();
        } else {
          timeBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.protos.Time time = 1;</code>
       */
      public Builder addTime(
          int index, com.protos.TimesProtos.Time.Builder builderForValue) {
        if (timeBuilder_ == null) {
          ensureTimeIsMutable();
          time_.add(index, builderForValue.build());
          onChanged();
        } else {
          timeBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.protos.Time time = 1;</code>
       */
      public Builder addAllTime(
          java.lang.Iterable<? extends com.protos.TimesProtos.Time> values) {
        if (timeBuilder_ == null) {
          ensureTimeIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, time_);
          onChanged();
        } else {
          timeBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.protos.Time time = 1;</code>
       */
      public Builder clearTime() {
        if (timeBuilder_ == null) {
          time_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          timeBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.protos.Time time = 1;</code>
       */
      public Builder removeTime(int index) {
        if (timeBuilder_ == null) {
          ensureTimeIsMutable();
          time_.remove(index);
          onChanged();
        } else {
          timeBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.protos.Time time = 1;</code>
       */
      public com.protos.TimesProtos.Time.Builder getTimeBuilder(
          int index) {
        return getTimeFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.protos.Time time = 1;</code>
       */
      public com.protos.TimesProtos.TimeOrBuilder getTimeOrBuilder(
          int index) {
        if (timeBuilder_ == null) {
          return time_.get(index);  } else {
          return timeBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.protos.Time time = 1;</code>
       */
      public java.util.List<? extends com.protos.TimesProtos.TimeOrBuilder> 
           getTimeOrBuilderList() {
        if (timeBuilder_ != null) {
          return timeBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(time_);
        }
      }
      /**
       * <code>repeated .com.protos.Time time = 1;</code>
       */
      public com.protos.TimesProtos.Time.Builder addTimeBuilder() {
        return getTimeFieldBuilder().addBuilder(
            com.protos.TimesProtos.Time.getDefaultInstance());
      }
      /**
       * <code>repeated .com.protos.Time time = 1;</code>
       */
      public com.protos.TimesProtos.Time.Builder addTimeBuilder(
          int index) {
        return getTimeFieldBuilder().addBuilder(
            index, com.protos.TimesProtos.Time.getDefaultInstance());
      }
      /**
       * <code>repeated .com.protos.Time time = 1;</code>
       */
      public java.util.List<com.protos.TimesProtos.Time.Builder> 
           getTimeBuilderList() {
        return getTimeFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.protos.TimesProtos.Time, com.protos.TimesProtos.Time.Builder, com.protos.TimesProtos.TimeOrBuilder> 
          getTimeFieldBuilder() {
        if (timeBuilder_ == null) {
          timeBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.protos.TimesProtos.Time, com.protos.TimesProtos.Time.Builder, com.protos.TimesProtos.TimeOrBuilder>(
                  time_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          time_ = null;
        }
        return timeBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.protos.Times)
    }

    // @@protoc_insertion_point(class_scope:com.protos.Times)
    private static final com.protos.TimesProtos.Times DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.protos.TimesProtos.Times();
    }

    public static com.protos.TimesProtos.Times getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Times>
        PARSER = new com.google.protobuf.AbstractParser<Times>() {
      public Times parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Times(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Times> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Times> getParserForType() {
      return PARSER;
    }

    public com.protos.TimesProtos.Times getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_protos_Time_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_protos_Time_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_protos_Times_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_protos_Times_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016sd_times.proto\022\ncom.protos\"?\n\004Time\022\n\n\002" +
      "id\030\001 \001(\005\022\014\n\004nome\030\002 \001(\t\022\014\n\004data\030\003 \001(\t\022\017\n\007" +
      "titulos\030\004 \001(\t\"\'\n\005Times\022\036\n\004time\030\001 \003(\0132\020.c" +
      "om.protos.TimeB\031\n\ncom.protosB\013TimesProto" +
      "sb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_protos_Time_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_protos_Time_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_protos_Time_descriptor,
        new java.lang.String[] { "Id", "Nome", "Data", "Titulos", });
    internal_static_com_protos_Times_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_protos_Times_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_protos_Times_descriptor,
        new java.lang.String[] { "Time", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
